In [4]:
import numpy as np

a=np.array([1,2,3])
b=np.array([[4,5,6],[7,8,9]])

In [ ]:
b.shape  # to get shape
a.shape

(3,)

In [ ]:
a.ndim #to get dimensions
a.dtype #to get data type
a.itemsize # to get byte length
a.size #to get length of array

3

In [18]:
b[1,2]
b[:,1]=[2,3]
print(b)

[[4 2 6]
 [7 3 9]]


In [20]:
x=np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])
x[0,1,0]

np.int64(3)

In [ ]:
a=np.zeros((2,3)) #to initialize zero matrix
a
b=np.ones((2,3))
b
c=np.full((5,5),22) #to initialize with any given number
c

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [36]:
np.random.rand(4,2)
np.random.randint(10,size=(4,2))

array([[5, 6],
       [8, 3],
       [9, 4],
       [7, 1]], dtype=int32)

In [ ]:
np.identity(3) #to get identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
y=np.repeat(x,3,axis=1)
y

array([[[1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4]],

       [[5, 6],
        [5, 6],
        [5, 6],
        [7, 8],
        [7, 8],
        [7, 8]]])

In [52]:
a=np.ones((5,5))
a[1:4,1:4]=0
a[2,2]=9
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a=np.array([1,2,3])
b=a.copy()  # use .copy() since b=a changes a if changes are made in b
b[0]=100
b

array([100,   2,   3])

In [63]:
print(a+2)
print(a-2)
print(a/2)
print(a*2)
np.sin(a)
print(a*b)


[3 4 5]
[-1  0  1]
[0.5 1.  1.5]
[2 4 6]
[100   4   9]


In [75]:
a=np.ones((3,3))
b=np.full((3,3),2)
np.matmul(a,b)
np.linalg.det(b)


np.float64(0.0)

In [80]:
np.sum(a)
np.min(a)
np.max(a)
np.mean(a)

np.float64(1.0)

In [84]:
a.reshape((1,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [87]:
np.vstack((a,b))
np.hstack((a,b))

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [92]:
a=np.genfromtxt('data.txt',delimiter=',')

In [94]:
a[a>7]

array([9., 9., 9., 9., 9., 9., 8., 9., 8., 9., 9., 8., 9., 8., 9., 9., 8.,
       8., 9., 9.])