In [1]:
l1=[1,2,3]


In [2]:
import numpy as np

l1=[1,2,3,4]

arr1=np.array(l1)

type(arr1)


numpy.ndarray

In [3]:
arr1+10

array([11, 12, 13, 14])

In [4]:
arr1.ndim
arr1.shape

arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr4.shape

(3, 3)

In [5]:
arr6=np.arange(3,21)
arr7=arr6.reshape(3,6)
arr7.shape



(3, 6)

In [11]:
arr2=[1,2,3,4,5,6,7,8,9]
arr2[-1:-5:-1]

[9, 8, 7, 6]

In [19]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4[[2,1]])

[[7 8 9]
 [4 5 6]]


In [21]:
print(arr4[1:,1:3])

[[5 6]
 [8 9]]


In [23]:
print(arr4[:2,[0,2]])

[[1 3]
 [4 6]]


In [ ]:
print(arr4.mean(axis=0))
np.sqrt(arr4)


[4. 5. 6.]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [30]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
print(arr1.var())

print(arr1)

1.25
[1 2 3 4]


In [35]:
a=arr1.mean()
print(a)
suma=0
for i in range(arr1.size):
    suma+=(a-arr1[i])**2
s=suma/arr1.size
print(s)


2.5
1.25


# variance

$(x_i - u_x)^2/N$

In [38]:
ans=np.sum(np.pow(arr1-np.mean(arr1),2))/np.size(arr1)
print(ans)

1.25


In [39]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
x=np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [47]:
x.diagonal()
b=np.arange(25).reshape(5,5)
x.dot(b)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [49]:
np.vstack((x,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
np.hstack((x,b))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

In [ ]:
np.concatenate([x,b],axis=1) #horizontal stacking for axis=1 and vertical for axis=0

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

In [55]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [96]:
np.random.randint(1,5,10)

array([1, 3, 4, 2, 4, 2, 1, 2, 3, 3], dtype=int32)

In [102]:
a=np.arange(1,21)
print(a)
b=np.random.shuffle(a)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[19  9  4  2  1  7 11  6 20 13 14 17 12 18 15  3 16 10  8  5]
