In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [12]:
voc_size=10000

In [13]:
onehot=[one_hot(word,voc_size)for word in sent]
onehot

[[9045, 5727, 2641, 2322],
 [9045, 5727, 2641, 4168],
 [9045, 4223, 2641, 7340],
 [1072, 7709, 9709, 2769, 19],
 [1072, 7709, 9709, 2769, 6336],
 [1230, 9045, 9714, 2641, 8015],
 [8178, 5623, 7058, 2769]]

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(onehot,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 9045, 5727, 2641, 2322],
       [   0,    0,    0,    0, 9045, 5727, 2641, 4168],
       [   0,    0,    0,    0, 9045, 4223, 2641, 7340],
       [   0,    0,    0, 1072, 7709, 9709, 2769,   19],
       [   0,    0,    0, 1072, 7709, 9709, 2769, 6336],
       [   0,    0,    0, 1230, 9045, 9714, 2641, 8015],
       [   0,    0,    0,    0, 8178, 5623, 7058, 2769]], dtype=int32)

In [18]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 9045, 5727, 2641, 2322], dtype=int32)

In [23]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[-0.03139158,  0.04004276, -0.02897966,  0.00855626, -0.03659731,
         0.01687751, -0.02221785,  0.01357046, -0.01246439,  0.02647555],
       [-0.03139158,  0.04004276, -0.02897966,  0.00855626, -0.03659731,
         0.01687751, -0.02221785,  0.01357046, -0.01246439,  0.02647555],
       [-0.03139158,  0.04004276, -0.02897966,  0.00855626, -0.03659731,
         0.01687751, -0.02221785,  0.01357046, -0.01246439,  0.02647555],
       [-0.03139158,  0.04004276, -0.02897966,  0.00855626, -0.03659731,
         0.01687751, -0.02221785,  0.01357046, -0.01246439,  0.02647555],
       [-0.00783866, -0.01078713,  0.01092806, -0.04295713,  0.00767655,
         0.02864665,  0.01372439,  0.02146783, -0.04539755,  0.01799479],
       [ 0.00644492,  0.04011846, -0.02871794,  0.00213491,  0.00504708,
         0.04247996,  0.03711401,  0.00620185, -0.04222752,  0.02097012],
       [-0.04557154,  0.01851184,  0.01081668,  0.00710823, -0.00030871,
        -0.04208769, -0.00279881, -0.04053222